input: ./examples/Rapha_Racing_UAT_Imp_Doc_V2.xlsx
sheets:
  - Networking Services
  - Storage & Compute Services
  - Database
  - Security Groups
  - IAM
  - Additional Services
resources:
  - Networking
  - Subnets
  - VPC Endpoints
  - VPN Gateway
  - Route53
  - Certificate Manager
  - EC2 Standalone Instances
  - EC2 Autoscaling Groups
  - Network Load Balancers
  - Application Load Balancers
  - Target Groups
  - S3 Buckets
  - EFS
  - RDS
  - Elasticache - Redis
  - Security Group
  - IAM Resource
  - CodeDeploy
