input: ./examples/Rapha_Racing_UAT_Imp_Doc_V2.xlsx
sheets:
  - Summary
  - Networking Services
  - Storage & Compute Services
  - Database
  - Security Groups
  - IAM
  - Additional Services
resources:
  - Networking
  - Subnetworks
  - VPC Endpoints
  - VPN Gateway
  - Route53
  - Certificate Manager
  - EC2 Standalone Instances
  - EC2 Autoscaling Groups
  - Network Load Balancers
  - Application Load Balancers
  - Target Groups
  - S3 Buckets
  - EFS
  - RDS
  - Elasticache - Redis
  - Security Group
  - IAM Resource
  - CodeDeploy
resourcesMap:
  Summary:
    sheet: "Summary"
    key: "B"
    values: "C"
    rows: "10 11 12 13 16 17 18 19 20 23 24"
